openapi: 3.0.0
info:
  title: Kms Backend
  version: 1.0.0
servers:
- url: /
paths: {}
components:
  schemas:
    Post:
      properties:
        author:
          description: Author of the post.
          readOnly: true
          type: AVUser
          x-object-index: default
          x-object-queryable: true
        rootPost:
          description: Root post if this post is a re-post, otherwise set to `null`
          readOnly: true
          type: Post
          x-object-index: default
          x-object-queryable: true
        parentPost:
          description: Parent post if this post is a re-post, otherwise set to `null`
          readOnly: true
          type: Post
          x-object-index: default
          x-object-queryable: true
        title:
          description: Required, title of the post.
          maxLength: 30
          minLength: 1
          readOnly: true
          type: string
        content:
          description: Content of the post.
          maxLength: 300
          minLength: 0
          readOnly: true
          type: string
        countThumbup:
          description: count number of thumbup in PostReaction.
          minimum: 0
          readOnly: true
          type: integer
        countComment:
          minimum: 0
          readOnly: true
          type: integer
        countRepost:
          minimum: 0
          readOnly: true
          type: integer
        repliedAt:
          description: Latest replied time (include comment and re-post)
          format: date
          readOnly: true
          type: string
          x-object-index: default
        development:
          description: Differentiate the posts version, true is beta.
          readOnly: true
          type: boolean
          x-object-index: default
      required:
      - author
      - content
      - title
      type: object
    Comment:
      properties:
        post:
          description: The post comment is replied to.
          readOnly: true
          type: Post
          x-object-index: default
          x-object-queryable: true
        author:
          description: Author of the comment.
          readOnly: true
          type: AVUser
        parentComment:
          description: Parent comment if this comment is replied to comment, otherwise
            set to `null`
          type: Comment
        content:
          description: Content of the comment.
          minLength: 1
          type: string
      required:
      - author
      - content
      - post
      type: object
    PostReaction:
      properties:
        post:
          readOnly: true
          type: Post
          x-object-index: default
          x-object-queryable: true
        author:
          readOnly: true
          type: AVUser
        emoji:
          description: Reaction of the post.
          enum:
          - thumbup
          type: string
      required:
      - author
      - emoji
      - post
      type: object
      x-object-cross-unique-index:
      - post
      - author
